apiVersion: v1
kind: ConfigMap
metadata:
    name: alertmanager-config
    namespace: monitoring
data:
    config.yml: |-
        global:
        templates:
        - '/etc/alertmanager/*.tmpl'
        route:
          receiver: alert-emailer
          group_by: ['alertname', 'priority']
          group_wait: 10s
          repeat_interval: 30m

        receivers:
        - name: alert-emailer
          email_configs:
          - to: alert@gmail.com
            send_resolved: false
            from: alert@gmail.com
            smarthost: smtp.gmail.com:25
            require_tls: false
